### ISSUE TITLE
support zk versions prior to 3.4

### ISSUE THREAD

**Issue by phunt** [andreisavu/zookeeper-monitoring#1]
Any way you could have something (a script?) that converts "stat" output (etc..., and provides defaults for metrics not available prior to 3.4) for users running older versions of ZK? It would really enable more people to try it out, granted with reduced metric coverage.

**Comment by andreisavu** [comment]
Sounds like a good idea because 3.4.0 is not going to be released very soon. I will change the ZooKeeperServer class to try to reconstruct a part of the output of 'mntr' command using 'stat'.

**Comment by andreisavu** [comment]
fixed and closed by commit aac2017e417480292879206f27467f3f8e1e013a
