### ISSUE TITLE
unreachable should be critical

### ISSUE THREAD

**Issue by Maexotic** [andreisavu/zookeeper-monitoring#4]
Shouldn't a missing key (eg because the host/service is down) result in an critical error?

<pre>
*** check_zookeeper.py.orig 2013-02-15 15:31:48.417663551 +0100
--- check_zookeeper.py  2013-02-15 15:23:33.100174871 +0100
***************
*** 47,55 ****
--- 47,57 ----
              return 2
  
          warning_state, critical_state, values = [], [], []
+   key_found = (opts.key is None)
          for host, stats in cluster_stats.items():
              if opts.key in stats:
  
+       key_found = True
                  value = stats[opts.key]
                  values.append('%s=%s;%s;%s' % (host, value, warning, critical))
  
***************
*** 60,65 ****
--- 62,72 ----
                      critical_state.append(host)
  
          values = ' '.join(values)
+ 
+   if not key_found:
+             print 'Critical "%s" %s!|%s' % (opts.key, ', '.join(critical_state), values)
+             return 2
+ 
          if critical_state:
              print 'Critical "%s" %s!|%s' % (opts.key, ', '.join(critical_state), values)
              return 2
</pre>

**Comment by andreisavu** [comment]
Please use https://issues.apache.org/jira/browse/ZOOKEEPER to discuss this. The code is now part of the main tree.
